### ISSUE TITLE
Names sometimes display in wrong script/language

### ISSUE THREAD

**Issue by jpastva** [jweisman/primo-explore-lod-author-card#4]
This issue seems to be coming from the bibcard API and displaying in the Primo author card, so I'm not sure if this is the correct repo for reporting. But we've noticed in test implementations that some author names are returning results in other languages/scripts. Examples include F. Scott Fitzgerald (http://viaf.org/viaf/100254195, Arabic), James Joyce (http://viaf.org/viaf/44300643, Arabic), and Walt Whitman (http://viaf.org/viaf/2478331, Cyrillic). Running the names directly through the bibcard API returns the same result.

![image](https://user-images.githubusercontent.com/9001461/123481961-7c49ec80-d5d2-11eb-9b49-78fa35203d02.png)

![image](https://user-images.githubusercontent.com/9001461/123482168-d2b72b00-d5d2-11eb-85a8-7059a54ca0d8.png)

**Comment by jweisman** [comment]
Hi @jpastva - thanks for reporting your issue! It seems that the language handling is not quite working for LC requests. I've removed the language from the request and it seems to me to work better (checked on a full record in our [test instance](https://tr-integration.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma991413020000541&vid=TR_INTEGRATION_INST:LD))

Can you let us know how it looks from your side?

**Comment by jpastva** [comment]
@jweisman I tested the above mentioned authors, and the names are now returned in the expected script. I'll keep an eye out for any other unusual behaviors, but it looks like you fixed it. Thanks for the quick response, we're looking forward to implementing this!

**Comment by jweisman** [comment]
Good to hear- thanks for the feedback. Let us know if you see any other strange behavior.
